#!/bin/sh
#
# Start the wifi....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/wifi

case "$1" in
  start)
	printf "Starting network: "
	/root/connect_wifi.sh
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifconfig wlan0 down
	/sbin/rmmod esp8089
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

